### ISSUE TITLE
Светогрибы

### ISSUE THREAD

**Issue by doublechest0** [Space-Stories/space-station-14#10]
https://discord.com/channels/1111698541841240164/1226846726586105896/1226981697178832917

**Comment by DenisShvalov** [comment]
С этими грибами думаю нужно добавить систему защищенного света, не выключаемого тенеморфом - те же светящиеся овощи, грибы, лампы боргов и его глаза

**Comment by doublechest0** [comment]
> С этими грибами думаю нужно добавить систему защищенного света, не выключаемого тенеморфом - те же светящиеся овощи, грибы, лампы боргов и его глаза

Так как теперь способность просто бьет лампы и выключает фонарики, то это уже неактуально.

**Comment by doublechest0** [comment]
Оффы делают.
