### ISSUE TITLE
Notice Of Copyright Violation

### ISSUE THREAD

**Issue by VMSolidus** [Space-Stories/space-station-14#104]
Attention, I am VMSolidus, founder and representative for Einstein Engines, and the legal codeowner involved in this dispute. Space-Stories is in violation of the terms of the license for all code present in this commit: https://github.com/Space-Stories/space-station-14/commit/8381c2bc38c445a7ab4e7c14a63be32143440129

This code is identical to code that I am personally one of two codeowners of, the other being John Station from Goobstation. BOTH of our permission is required for this code to be present in any repository not licensed as AGPLv3. I was not asked, and have not provided such permission. The original source of the violating code is https://github.com/Simple-Station/Einstein-Engines/pull/341

Space-Stories, in porting code licensed by the terms of AGPLv3, as stated here, https://github.com/Simple-Station/Einstein-Engines?tab=AGPL-3.0-1-ov-file , has violated the terms of this license. Space-Stories is hereby instructed to perform one of the following actions:

1. IMMEDIATELY remove all code contained within the commit: https://github.com/Space-Stories/space-station-14/commit/8381c2bc38c445a7ab4e7c14a63be32143440129
2. Change the License of the Space-Stories repository to AGPLv3. 

If neither of these actions are performed by 16:00 EST, on 9/26/2024, I will issue a DMCA Takedown Notice to Space-Stories.

**Comment by doublechest0** [comment]
All code has been removed: https://github.com/Space-Stories/space-station-14/commit/5bf153c13d2a6aea5289f3941449ca6f6430d887. Servers will be updated immediately after the end of the round.
