### ISSUE TITLE
Доступы кт боргам

### ISSUE THREAD

**Issue by pheenty** [Space-Stories/space-station-14#111]
У боргов нет доступов КТ. По сути фича - доступа ЦК (и тем более синдиката, но там очевидно) у них тоже нет, они предназначены для работы на станции, а не на кт, но могу добавить. Тем более, ИКТ всё ещё имеет навык робототехники, причём непонятно, зачем

**Comment by doublechest0** [comment]
Боргам не нужен доступ КТ в текущих реалях.
