### ISSUE TITLE
Починить ClothingWhitelist

### ISSUE THREAD

**Issue by doublechest0** [Space-Stories/space-station-14#183]
Она сломана, скафы ЯО не взрываются.

**Comment by pheenty** [comment]
```c#
if (comp.Blacklist != null && !_whitelistSystem.IsWhitelistFail(comp.Blacklist, args.Equipee) || comp.Blacklist == null)
            if (comp.Whitelist != null && _whitelistSystem.IsWhitelistFail(comp.Whitelist, args.Equipee)) return;
``` 

Что за ужас...

Если блеклист не нулевой и в нём есть энтити, либо если он нулевой, то
   если вайтлист не нулевой и в нём нет энтити, то не будем взрывать энтити.
   
Блеклисты на всех скафах нулевые (поэтому первая проверка всегда проходится). А если бы он был, то наоборот, нам надо чтобы в нём НЕ было энтити, которое мы НЕ хотим взрывать.
А в вайтлисте НЕТ энтити, которую мы ХОТИМ взорвать (это же вайтлист, на кого МОЖНО надеть скаф), поэтому на тех, кого мы ХОТИМ взорвать, проверка проходится. А те, кого взрывать как раз НЕ надо, живут на последующих проверках по фракции.

А ещё вместо проверок на null в EntityWhitelistSystem есть более удобные методы.

Без обид, но это ЛЮТЫЙ говнокод, который ещё и работает ровно наоборот от задуманного. Щас буду чинить.

**Comment by doublechest0** [comment]
> ```cs
> if (comp.Blacklist != null && !_whitelistSystem.IsWhitelistFail(comp.Blacklist, args.Equipee) || comp.Blacklist == null)
>             if (comp.Whitelist != null && _whitelistSystem.IsWhitelistFail(comp.Whitelist, args.Equipee)) return;
> ```
> 
> Что за ужас...
> 
> Если блеклист не нулевой и в нём есть энтити, либо если он нулевой, то если вайтлист не нулевой и в нём нет энтити, то не будем взрывать энтити.
> 
> Блеклисты на всех скафах нулевые (поэтому первая проверка всегда проходится). А если бы он был, то наоборот, нам надо чтобы в нём НЕ было энтити, которое мы НЕ хотим взрывать. А в вайтлисте НЕТ энтити, которую мы ХОТИМ взорвать (это же вайтлист, на кого МОЖНО надеть скаф), поэтому на тех, кого мы ХОТИМ взорвать, проверка проходится. А те, кого взрывать как раз НЕ надо, живут на последующих проверках по фракции.
> 
> А ещё вместо проверок на null в EntityWhitelistSystem есть более удобные методы.
> 
> Без обид, но это ЛЮТЫЙ говнокод, который ещё и работает ровно наоборот от задуманного. Щас буду чинить.

Капитан Очевидность

**Comment by pheenty** [comment]
> > ```cs
> > if (comp.Blacklist != null && !_whitelistSystem.IsWhitelistFail(comp.Blacklist, args.Equipee) || comp.Blacklist == null)
> >             if (comp.Whitelist != null && _whitelistSystem.IsWhitelistFail(comp.Whitelist, args.Equipee)) return;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Что за ужас...
> > Если блеклист не нулевой и в нём есть энтити, либо если он нулевой, то если вайтлист не нулевой и в нём нет энтити, то не будем взрывать энтити.
> > Блеклисты на всех скафах нулевые (поэтому первая проверка всегда проходится). А если бы он был, то наоборот, нам надо чтобы в нём НЕ было энтити, которое мы НЕ хотим взрывать. А в вайтлисте НЕТ энтити, которую мы ХОТИМ взорвать (это же вайтлист, на кого МОЖНО надеть скаф), поэтому на тех, кого мы ХОТИМ взорвать, проверка проходится. А те, кого взрывать как раз НЕ надо, живут на последующих проверках по фракции.
> > А ещё вместо проверок на null в EntityWhitelistSystem есть более удобные методы.
> > Без обид, но это ЛЮТЫЙ говнокод, который ещё и работает ровно наоборот от задуманного. Щас буду чинить.
> 
> Капитан Очевидность

Меня больше смущает, что до какого-то момента это каким-то образом работало

**Comment by doublechest0** [comment]
> > > ```cs
> > > if (comp.Blacklist != null && !_whitelistSystem.IsWhitelistFail(comp.Blacklist, args.Equipee) || comp.Blacklist == null)
> > >             if (comp.Whitelist != null && _whitelistSystem.IsWhitelistFail(comp.Whitelist, args.Equipee)) return;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Что за ужас...
> > > Если блеклист не нулевой и в нём есть энтити, либо если он нулевой, то если вайтлист не нулевой и в нём нет энтити, то не будем взрывать энтити.
> > > Блеклисты на всех скафах нулевые (поэтому первая проверка всегда проходится). А если бы он был, то наоборот, нам надо чтобы в нём НЕ было энтити, которое мы НЕ хотим взрывать. А в вайтлисте НЕТ энтити, которую мы ХОТИМ взорвать (это же вайтлист, на кого МОЖНО надеть скаф), поэтому на тех, кого мы ХОТИМ взорвать, проверка проходится. А те, кого взрывать как раз НЕ надо, живут на последующих проверках по фракции.
> > > А ещё вместо проверок на null в EntityWhitelistSystem есть более удобные методы.
> > > Без обид, но это ЛЮТЫЙ говнокод, который ещё и работает ровно наоборот от задуманного. Щас буду чинить.
> > 
> > 
> > Капитан Очевидность
> 
> Меня больше смущает, что до какого-то момента это каким-то образом работало

Оно было написано очень давно до рефактора EntityWhitelist и сломалось от одного апстрима
