### ISSUE TITLE
Feature: Роль Юриста

### ISSUE THREAD

**Issue by SHEGARE** [Space-Stories/space-station-14#199]
## Чек-лист:
1. Код
- [ ] **Роль юриста:**
- Корректировка "JobLawyer"
- Добавить возможность взять роль юриста _на всех картах_
2. Маппинг
- [ ] Добавить "SpawnPointLawyer" _на все карты_

**Comment by pheenty** [comment]
В принципе, можно ключ АВД поменять под юридический, чтобы он давал доступы к частоте СБ и к юридической. У юристов будет юридический и общий ключ, у авд юридический, общий и командный. Сервер СБ на картах поменять на юридический сервер.

**Comment by SHEGARE** [comment]
> В принципе, можно ключ АВД поменять под юридический, чтобы он давал доступы к частоте СБ и к юридической. У юристов будет юридический и общий ключ, у авд юридический, общий и командный. Сервер СБ на картах поменять на юридический сервер. Верней даже в прототипе СБшного сервера поменять просто ключ на юридический, и всё, чтобы не менять все карты

Суть в том чтобы любой мог обратиться к юр роли, через рацию

**Comment by pheenty** [comment]
> > В принципе, можно ключ АВД поменять под юридический, чтобы он давал доступы к частоте СБ и к юридической. У юристов будет юридический и общий ключ, у авд юридический, общий и командный. Сервер СБ на картах поменять на юридический сервер. Верней даже в прототипе СБшного сервера поменять просто ключ на юридический, и всё, чтобы не менять все карты
> 
> Суть в том чтобы любой мог обратиться к юр роли, через рацию

То есть дать юр. рацию ВСЕМ? Чё за бред

**Comment by pheenty** [comment]
Давай теперь дадим карго рацию сервиса, чтобы они могли просить у поваров суп на продажу, а учёным рацию меда, чтобы просить химикаты для активации узла арта

**Comment by SHEGARE** [comment]
> Давай теперь дадим карго рацию сервиса, чтобы они могли просить у поваров суп на продажу, а учёным рацию меда, чтобы просить химикаты для активации узла арта

Только жалобы могут быть на любого. Просто переношу нытьё про ОПРС и его нарушение из общей частоты в Юридическую

**Comment by pheenty** [comment]
> > Давай теперь дадим карго рацию сервиса, чтобы они могли просить у поваров суп на продажу, а учёным рацию меда, чтобы просить химикаты для активации узла арта
> 
> Только жалобы могут быть на любого. Просто переношу нытьё про ОПРС и его нарушение из общей частоты в Юридическую

А какой смысл, если частота будет у всех? Лучше в допроску и у кабинета АВД тогда поставить интерком с юр частотой

**Comment by SHEGARE** [comment]
> > > Давай теперь дадим карго рацию сервиса, чтобы они могли просить у поваров суп на продажу, а учёным рацию меда, чтобы просить химикаты для активации узла арта
> > 
> > 
> > Только жалобы могут быть на любого. Просто переношу нытьё про ОПРС и его нарушение из общей частоты в Юридическую
> 
> А какой смысл, если частота будет у всех? Лучше в допроску и у кабинета АВД тогда поставить интерком с юр частотой

А если сотрудника посадили без суда и следствия?

**Comment by pheenty** [comment]
> > > > Давай теперь дадим карго рацию сервиса, чтобы они могли просить у поваров суп на продажу, а учёным рацию меда, чтобы просить химикаты для активации узла арта
> > > 
> > > 
> > > Только жалобы могут быть на любого. Просто переношу нытьё про ОПРС и его нарушение из общей частоты в Юридическую
> > 
> > 
> > А какой смысл, если частота будет у всех? Лучше в допроску и у кабинета АВД тогда поставить интерком с юр частотой
> 
> А если сотрудника посадили без суда и следствия?

Если щиткурство такой степени, ничто не мешает и гарнитуру у человека забрать

**Comment by SHEGARE** [comment]
> > > > > Давай теперь дадим карго рацию сервиса, чтобы они могли просить у поваров суп на продажу, а учёным рацию меда, чтобы просить химикаты для активации узла арта
> > > > 
> > > > 
> > > > Только жалобы могут быть на любого. Просто переношу нытьё про ОПРС и его нарушение из общей частоты в Юридическую
> > > 
> > > 
> > > А какой смысл, если частота будет у всех? Лучше в допроску и у кабинета АВД тогда поставить интерком с юр частотой
> > 
> > 
> > А если сотрудника посадили без суда и следствия?
> 
> Если щиткурство такой степени, ничто не мешает и гарнитуру у человека забрать

Го лучше в ГС ДСа продолжим, я на паре, плюс в войсе быстрее обсудим
