### ISSUE TITLE
Feature: Имплант "кодировщик"

### ISSUE THREAD

**Issue by SHEGARE** [Space-Stories/space-station-14#244]
## Чек-лист:
- [ ] Сделать имплант, который заставляет носителя блевать, если в желудке оказывается спиртное
- [ ] Добавить 3 таких импланта в шкаф ГВ
- [ ] Добавить ящик с такими имплантами в заказы Карго, за 5000 кредитов. В одном ящике 3 импланта

**Comment by CatBackGround** [comment]
Всех Дворфов закодируют...

**Comment by SHEGARE** [comment]
> Всех Дворфов закодируют...

Тсссс
