### ISSUE TITLE
Feature: Пассажиры теперь ассистенты с доступом в техи

### ISSUE THREAD

**Issue by doublechest0** [Space-Stories/space-station-14#250]
Переименовать пассажиров в ассистентов, выдать им доступ в техи.

На подобии сс13, где пассажиры это не глупые новички, а глупые новички, целью которых является помощь специалистам. (Например, инженер взял с собой ассистентов для строительства базы на астеройде, шахтеры взяли ассистентов себе в подмастерье)

**Comment by pheenty** [comment]
То что у них нет доступа, это просто взято с корвакса, от контента которого (кроме разве что АВД) мы медленно избавляемся.
А зачем их переименовать в ассистенты? Они уже были ассистентами в сс14, но их оффы переименовали в пассажиров. Доступ в техи при этом у оффов у них всегда был и есть сейчас

**Comment by doublechest0** [comment]
Пассажир звучит как обычный экипаж станции, хотя мы на научной станции, где у всех есть работа.

**Comment by pheenty** [comment]
> Пассажир звучит как обычный экипаж станции, хотя мы на научной станции, где у всех есть работа.

Ну хз. Я лично за доступ в техи двумя руками за, но "пассажир" мне больше нравится
