### ISSUE TITLE
Flaw: возможно, в allatonce должен быть тенеморф. В alleratonce точно должен быть.

### ISSUE THREAD

**Issue by pheenty** [Space-Stories/space-station-14#264]
![image](https://github.com/user-attachments/assets/ec034e48-ecc7-4591-b331-f3a82894a7f3)

**Comment by SHEGARE** [comment]
![i (8)](https://github.com/user-attachments/assets/d6a38d66-3771-4637-b2ff-9aaa6ffdc8c3)
