### ISSUE TITLE
Сделать админ призраков реально невидимыми.

### ISSUE THREAD

**Issue by doublechest0** [Space-Stories/space-station-14#7]
Их одежда и вещи в руках видны, когда они в невидимке.

**Comment by SoulFN** [comment]
В принципе, мало смысла в способности невидимости, потому что можно с помощью команды scale себя уменьшить до невидимого состояния.

**Comment by pheenty** [comment]
Может им Stealth компонент просто дать?

**Comment by pheenty** [comment]
Неидеальное решение из-за шейдеров, но как костыль пойдёт

**Comment by doublechest0** [comment]
Можно просто ревертнуть не работающий код.
Не особо кому нужно.

**Comment by doublechest0** [comment]
@pheenty Удали код скрытия админ призраков
